apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: insuretech-app-hpa
  namespace: insuretech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: insuretech-app-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # HPA BASED ON MEMORY UTILIZATION
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 50
