apiVersion: v1
kind: Service
metadata:
  name: insuretech-service
  namespace: insuretech
  labels:
    prometheus-monitored: "true"
spec:
  selector:
    app: scaletestapp
  ports:
    - port: 8080
  type: NodePort
